In [1]:
import numpy as np
from sklearn import neighbors
import math

import xlrd

def load(filename,class_column,skiprow):
    data = xlrd.open_workbook(filename)  
    table = data.sheets()[0]  
    nrows = table.nrows  
    temp_attr = []
    temp_class = []
    for i in range(nrows):  
        if i in skiprow:  
            continue
        temp_attr.append(table.row_values(i)[0:32])
        temp_class.append(table.row_values(i)[31+class_column])

    data_attr = np.array(temp_attr)
    data_class = np.array(temp_class)
    data = np.column_stack((data_attr,data_class))
    return data

def myplan(train_data,test_data):

    # 训练集
    train_attrs = train_data[:,:32]
    train_class = train_data[:,32]

    knn = neighbors.KNeighborsClassifier()
    knn.fit(train_attrs, train_class)

    # 测试集
    test_attrs = test_data[:,:32]
    test_class = test_data[:,32]
    
    result = knn.predict(test_attrs)
    print(result)
    
    # 计算正确率
    count = 0
    for i in range(result.shape[0]):
        if test_class[i]==result[i]:
            count+=1

    print('result:',count/result.size)

if __name__ == '__main__':
    train_file = 'train.xls'
    test_file = 'test.xls'
    for i in range(1,7):
        class_column = i
        skip_column = (0,)
        train_set = load(train_file,class_column,skip_column)
        test_set = load(test_file,class_column,skip_column)
        myplan(train_set,test_set)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
result: 1.0
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
result: 0.85
[1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
result: 0.75
[1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
result: 0.5
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1.]
result: 0.7
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
result: 0.7
